import { angularRemoteName } from "./angular-names.js";

export function angularWorkspace(name: string, host: boolean): unknown {
  return {
    version: 1,
    projects: {
      [name]: {
        projectType: "application", root: "", sourceRoot: "src",
        architect: {
          build: { builder: "@angular-architects/native-federation:build", options: { target: `${name}:esbuild:production` }, configurations: { development: { target: `${name}:esbuild:development`, dev: true } } },
          serve: { builder: "@angular-architects/native-federation:build", options: { target: `${name}:serve-original:development`, dev: true, port: host ? 4200 : 4201 } },
          esbuild: {
            builder: "@angular-devkit/build-angular:application",
            options: { outputPath: `dist/${name}`, index: "src/index.html", browser: "src/main.ts", polyfills: ["zone.js", "es-module-shims"], tsConfig: "tsconfig.app.json", assets: [{ glob: "**/*", input: "public" }, { glob: "**/*", input: "src/assets", output: "assets" }], styles: ["src/styles.css"] },
            configurations: { production: { outputHashing: "all" }, development: { optimization: false, sourceMap: true } }
          },
          "serve-original": { builder: "@angular-devkit/build-angular:dev-server", configurations: { production: { buildTarget: `${name}:esbuild:production` }, development: { buildTarget: `${name}:esbuild:development` } }, defaultConfiguration: "development" }
        }
      }
    }
  };
}

function angularCompilerOptions(): Record<string, unknown> {
  return {
    target: "ES2022",
    module: "ES2022",
    moduleResolution: "bundler",
    strict: true,
    experimentalDecorators: true,
    useDefineForClassFields: false,
    lib: ["ES2022", "DOM"],
    skipLibCheck: true
  };
}

function angularTemplateCompilerOptions(): Record<string, unknown> {
  return { strictTemplates: true, strictInjectionParameters: true };
}

export function angularAppTsconfig(): unknown {
  return {
    compilerOptions: { ...angularCompilerOptions(), outDir: "./out-tsc/app" },
    angularCompilerOptions: angularTemplateCompilerOptions(),
    files: ["src/main.ts"],
    include: ["src/**/*.ts"]
  };
}

export function angularFederationConfig(name: string, host: boolean): string {
  return `// Generated by Atlas for @angular-architects/native-federation.
// Edit atlas.config.ts and application source; do not hand-edit this compatibility file.
// Native Federation requires this exact filename next to the Angular tsconfig.
const { readdirSync, existsSync } = require("node:fs");
const { join } = require("node:path");
const { withNativeFederation } = require("@angular-architects/native-federation/config");

const widgetsRoot = join(__dirname, "src/exported-widgets");
const widgetExposes = existsSync(widgetsRoot)
  ? Object.fromEntries(
      readdirSync(widgetsRoot, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => [
          \`./widgets/\${entry.name}\`,
          \`./src/exported-widgets/\${entry.name}/index.ts\`
        ])
    )
  : {};

module.exports = withNativeFederation({
  name: "${angularRemoteName(name)}",
  exposes: ${host ? "{}" : `{ "./entry": "./src/entry.ts", ...widgetExposes }`},
  // Product dependencies stay inside this build so hosts never impose their versions.
  shared: {},
  skip: ["rxjs/ajax", "rxjs/fetch", "rxjs/testing", "rxjs/webSocket"]
});
`;
}
