packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples/hosts/*'
  - 'examples/apps/*'
  - 'examples/e2e'

linkWorkspacePackages: true

allowBuilds:
  '@parcel/watcher': true
  core-js: false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sinon: false
