export {
  createAngularFederationConfig,
  createAngularFederationOptions,
  createReactAppViteConfig,
  createReactHostViteConfig,
  createReactWidgetEntries,
  FederationConfigError,
  type AngularFederationConfigOptions,
  type AngularFederationOptions,
  type AngularProjectExpose,
  type FederationConfigErrorOptions,
  type ReactFederationConfigOptions,
  type ReactWidgetEntriesOptions,
  type ShareAll,
  type SkipEntry,
  type WidgetEntry,
} from './dist/federation-config/index.cjs';
