"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FederationConfigError = exports.createReactWidgetEntries = exports.createReactHostViteConfig = exports.createReactAppViteConfig = exports.createAngularFederationOptions = exports.createAngularFederationConfig = void 0;
var index_cjs_1 = require("./dist/federation-config/index.cjs");
Object.defineProperty(exports, "createAngularFederationConfig", { enumerable: true, get: function () { return index_cjs_1.createAngularFederationConfig; } });
Object.defineProperty(exports, "createAngularFederationOptions", { enumerable: true, get: function () { return index_cjs_1.createAngularFederationOptions; } });
Object.defineProperty(exports, "createReactAppViteConfig", { enumerable: true, get: function () { return index_cjs_1.createReactAppViteConfig; } });
Object.defineProperty(exports, "createReactHostViteConfig", { enumerable: true, get: function () { return index_cjs_1.createReactHostViteConfig; } });
Object.defineProperty(exports, "createReactWidgetEntries", { enumerable: true, get: function () { return index_cjs_1.createReactWidgetEntries; } });
Object.defineProperty(exports, "FederationConfigError", { enumerable: true, get: function () { return index_cjs_1.FederationConfigError; } });
