export type BootstrapErrorCode =
  | 'DEPLOYMENT_INVALID'
  | 'CATALOG_INVALID'
  | 'HOST_MANIFEST_INVALID'
  | 'ARTIFACT_URL_REJECTED'
  | 'ARTIFACT_VERIFICATION_FAILED'
  | 'OVERRIDE_INVALID'
  | 'RESOURCE_UNAVAILABLE'
  | 'HOST_REMOTE_INVALID'
  | 'MODULE_LOADER_UNAVAILABLE'
  | 'HOST_MOUNT_FAILED'
  | 'BOOTSTRAP_TEMPLATE_INVALID';
